export function Footer() {
  return (
    <div 
      className="relative mx-auto max-w-[900px] px-8 pb-12 pt-16"
    >
      <div 
        className="rounded-3xl p-8 text-center"
        style={{
          background: 'rgba(0, 0, 0, 0.03)',
          border: '1px solid rgba(0, 0, 0, 0.05)',
        }}
      >
        <p 
          className="text-sm font-semibold text-black/60"
          style={{ fontFamily: 'Source Sans Pro, -apple-system, system-ui, sans-serif' }}
        >
          Generated by{' '}
          <span className="font-semibold text-black/80">Paeon AI</span>
          {' '}• Sources:{' '}
          <a 
            href="#" 
            className="font-medium text-black/70 underline decoration-black/30 hover:decoration-black/60"
          >
            CDSCO Label [Ref 1]
          </a>
          {', '}
          <a 
            href="#" 
            className="font-medium text-black/70 underline decoration-black/30 hover:decoration-black/60"
          >
            EMPA-REG [Ref 2]
          </a>
        </p>
        
        <div 
          className="mx-auto mt-4 h-px w-24"
          style={{ background: 'rgba(0, 0, 0, 0.1)' }}
        />
        
        <p 
          className="mt-4 text-xs font-normal text-black/40"
          style={{ fontFamily: 'Source Sans Pro, -apple-system, system-ui, sans-serif' }}
        >
          This AI-generated content is for informational purposes only and should not replace 
          professional medical advice.
        </p>
      </div>
    </div>
  );
}